# Generated by Django 5.2.12 on 2026-03-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='price_5a_side',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional fixed price for 5-a-side teams', max_digits=10),
        ),
        migrations.AddField(
            model_name='turf',
            name='price_7a_side',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional fixed price for 7-a-side teams', max_digits=10),
        ),
    ]
