# Generated by Django 5.2.12 on 2026-03-07 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0002_turf_price_5a_side_turf_price_7a_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_blocks', to='turfs.turf')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
