# Generated by Django 5.2.12 on 2026-03-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0003_maintenanceblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='price_11a_side',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional fixed price for 11-a-side teams', max_digits=10),
        ),
    ]
