# Generated by Django 5.2.12 on 2026-03-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='members',
            field=models.PositiveIntegerField(choices=[(5, '5-a-side'), (7, '7-a-side')], default=5),
        ),
    ]
