# Generated by Django 5.2.12 on 2026-03-08 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_members'),
        ('turfs', '0004_turf_price_11a_side'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='members',
            field=models.PositiveIntegerField(choices=[(5, '5-a-side'), (7, '7-a-side'), (11, '11-a-side')], default=5),
        ),
        migrations.CreateModel(
            name='CancelledBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=200)),
                ('turf_location', models.CharField(max_length=300)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('members', models.PositiveIntegerField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(default='Cancelled due to maintenance', max_length=500)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to='turfs.turf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cancelled_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
